### ISSUE TITLE
"headless"? 

### ISSUE THREAD

**Issue by danyaljj** [nittolese/gquestions#4]
Just a clarification on your terminology: 
What do you mean by "headless"?

**Comment by nittolese** [comment]
Hi @danyaljj , 
headless Chrome is an instance of Chrome without GUI. When do you start the script in this mode, you don't see the browser but it is running in background (you can check on your Task Manager).
It is useful when you're working on servers which don't have GUI (so-called headless environments).

Here you can find more info on [`Chrome headless`](https://developers.google.com/web/updates/2017/04/headless-chrome)

Regards!
