### ISSUE TITLE
MAX_DEPTH=1?

### ISSUE THREAD

**Issue by danyaljj** [nittolese/gquestions#5]
Looks like the maximum depth one can set is 1: 
https://github.com/nittolese/gquestions/blob/master/gquestions.py#L300-L305

What is the logic here?

**Comment by nittolese** [comment]
Hi @danyaljj , 
thanks for asking.
That piece of code is a bit messy right now, but don't worry: it's on the top of my to-do list for this repo.

When depth=0 -> It clicks only on first 3-4 questions and create  [this tree graph](https://i.gyazo.com/f1998e734148f5d67979e310cf7123aa.png)
When depth=1 -> It clicks on question 1 (level1),  then it clicks on the question appeared after the click on question 1 (level2) and gathers info about the last question appeared (level3). The tree graph generated is something [like this](https://i.gyazo.com/5f9677d13ba9845e0f38972e4d8c6ed3.png).

It should be:
When depth=0 -> Don't click on anything. Create a tree graph without any interaction with questions (so you should see only the first 3-4 questions).
When depth=1 -> It clicks only on first 3-4 questions and create the tree graph.
When depth=2 -> Same behavior as current depth=1 . 

MAX_DEPTH=1 is only a constant to validate the CLI args.
Feel free to contribute with a PR :)
